---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: headers
    version: v2
  name: headers-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headers
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: headers
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: quay.io/redhattraining/ossm-maven-simplest:2.0
        name: headers
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: headers
    version: v1
  name: headers-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headers
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: headers
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: quay.io/redhattraining/ossm-maven-simplest:1.0
        name: headers
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: headers
  name: headers
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: headers
status:
  loadBalancer: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: headers
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: headers-vs
spec:
  hosts:
  - "*"
  gateways:
  - headers
  http:
  - match:
    - uri:
        prefix: /headers
    rewrite:
      uri: /
    route:
    - destination:
        host: headers
        port:
          number: 8080
