apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chaos-error
spec:
  hosts:
  - recommendation
  http:
  - route:
    - destination:
        host: vertx-greet
    fault:
      abort:
        httpStatus: 500
        percentage:
          value: 50.0